### ISSUE TITLE
Development and production environment

### ISSUE THREAD

**Issue by hlac** [ugurkodak/COMP313_Team_4#3]
- Create a development environment that comes as close to the production environment as much as possible.
- Create development environment (setup and configuration instructions) so that each member will have the same setup.
- On the production environment, create a simple application to test round communication (e.g. ping to backend).  To check for things like authentication.
- Extract key components that allow development on localhost.

**Comment by ugurkodak** [comment]
Repository has a continuous deployment with Heroku so everybody can push for deployment. We need to create a database instance.

**Comment by ugurkodak** [comment]
Created a MongoDB instance using mLab. New users will be created accordingly.
