### ISSUE TITLE
Requirements gathering

### ISSUE THREAD

**Issue by hlac** [ugurkodak/COMP313_Team_4#4]
- Low-fidelity prototype.
- User stories and corresponding disaggregated tasks.

**Comment by hlac** [comment]
#2

**Comment by ugurkodak** [comment]
Low Fidelity Prototype
![untitled diagram](https://cloud.githubusercontent.com/assets/12514643/22562111/316da0fa-e949-11e6-9b0c-cbe483ecdba3.png)

**Comment by ugurkodak** [comment]
User stories will be documented as GitHub issues.
