### ISSUE TITLE
Design a UI for the homepage.

### ISSUE THREAD

**Issue by hlac** [ugurkodak/COMP313_Team_4#6]
#5

**Comment by ugurkodak** [comment]
![ui_home](https://cloud.githubusercontent.com/assets/12514643/22866935/eead0070-f14b-11e6-9c8d-5905e3be1cdf.png)

**Comment by ugurkodak** [comment]
No need to make a mock up for user registration and and account settings page. It will be a generic one.

**Comment by ghost** [comment]
Design Done.
